"""
Created on Fri Jun 16 13:13:27 2023

@author: Rajeswari
"""

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import traceback
#from fastapi import FastAPI

#async def main(query:str):
#async def main(path, query):
def generate_answer(query):
    try:  
        tokenizer = AutoTokenizer.from_pretrained("google/flan-t5-base")
        model = AutoModelForSeq2SeqLM.from_pretrained("google/flan-t5-base")
        
        # with open(path, 'r') as txt:
        #     context = txt.read()
        context = "User-defined patterns (reference) - IBM Documentation Skip to main content Documentation Announcements Product list Documentation Announcements Product list Search all of IBM Close All products IBM App Connect 11.0.0 Change version Change version12.011.0.0cloudcontainercontainers_cdcontainers_eussaas IBM App Connect Enterprise, Version 11.0.0.21 Operating Systems: AIX, Linux, Windows User-defined patterns (reference) Last Updated: 2023-05-22 View the reference information in this section to modify user-defined patterns and to create user-defined editors for your user-defined patterns. To write code to modify pattern instances when a pattern instance is generated by a pattern user, use the IBM® Integration API and the PHP API. To write code for user-defined editors, use the Java™ interfaces for user-defined editors. APIs To find information about APIs, see the following topics: IBM Integration API PHP API for user-defined patterns Java interfaces To find information about Java interfaces for creating user-defined editors, see Java interfaces for user-defined editors. PHP API for user-defined patterns Use the PHP API to write PHP code to develop user-defined pattern applications. Java interfaces for user-defined editors Use Java interfaces to write code for user-defined editors in your user-defined patterns. Parent topic: Arrow right Message flow development While IBM values the use of inclusive language, terms that are outside of IBM's direct influence, for the sake of maintaining user understanding, are sometimes required. As other industry leaders join IBM in embracing the use of inclusive language, IBM will continue to update the documentation to reflect those changes."
        
        t5query = f"Question: {query}. Context: {context}"
        inputs = tokenizer(t5query, return_tensors="pt")
        outputs = model.generate(**inputs, max_new_tokens=20)
        return tokenizer.batch_decode(outputs, skip_special_tokens=True)
    except Exception as e:
        traceback.print_exc()
        return f"An error has occured: {e}"

# query = "What is the use of PHP API for user-defined patterns"
# answer = "to write PHP code to develop user-defined pattern applications."